"use server";

import { updateTag } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { adminContext } from "@/lib/admin/context";
import type { FormState } from "@/lib/admin/form-state";
import { productSchema } from "@/lib/admin/validation";
import { PRODUCT_IMAGES_BUCKET } from "@/lib/supabase/public";

// Paths are generated by the admin image uploader; anything else is rejected.
const STORAGE_PATH = /^products\/[0-9a-f-]{36}\.(jpg|png|webp|avif)$/;
const isUuid = (value: string) => z.uuid().safeParse(value).success;
const field = (formData: FormData, key: string) => String(formData.get(key) ?? "");

function dbError(error: { code?: string; message: string }): FormState {
  if (error.code === "23505") {
    return {
      ok: false,
      message: "That URL or Etsy listing ID is already used by another product.",
      fieldErrors: { slug: ["Already in use"] },
    };
  }
  console.error("[admin/products]", error.message);
  return { ok: false, message: "Could not save the product. Please try again." };
}

export async function saveProduct(_prev: FormState, formData: FormData): Promise<FormState> {
  const { supabase } = await adminContext();
  const rawId = field(formData, "id");
  const productId = isUuid(rawId) ? rawId : null;

  const parsed = productSchema.safeParse({
    title: field(formData, "title"),
    slug: field(formData, "slug"),
    description: field(formData, "description"),
    price: field(formData, "price"),
    compareAt: field(formData, "compareAt"),
    categorySlug: field(formData, "categorySlug"),
    gender: field(formData, "gender"),
    lengthIn: field(formData, "lengthIn"),
    weightLbs: field(formData, "weightLbs"),
    stockQty: field(formData, "stockQty") || "0",
    status: field(formData, "status"),
    isFeatured: formData.get("isFeatured") === "on",
    badge: field(formData, "badge"),
    sortOrder: field(formData, "sortOrder") || "0",
    etsyListingId: field(formData, "etsyListingId"),
    seoTitle: field(formData, "seoTitle"),
    seoDescription: field(formData, "seoDescription"),
  });
  if (!parsed.success) {
    return { ok: false, message: "Please check the highlighted fields.", fieldErrors: z.flattenError(parsed.error).fieldErrors };
  }

  const v = parsed.data;

  // Products and collections share the /reborn-dolls/<slug> namespace.
  const { data: clash } = await supabase.from("categories").select("slug").eq("slug", v.slug).maybeSingle();
  if (clash) {
    return { ok: false, message: "A collection already uses this URL.", fieldErrors: { slug: ["Already used by a collection"] } };
  }

  const row = {
    title: v.title,
    slug: v.slug,
    description: v.description,
    price_pence: v.price,
    compare_at_price_pence: v.compareAt,
    category_slug: v.categorySlug,
    gender: v.gender,
    length_in: v.lengthIn,
    weight_lbs: v.weightLbs,
    stock_qty: v.stockQty,
    status: v.status,
    is_featured: v.isFeatured,
    badge: v.badge,
    sort_order: v.sortOrder,
    etsy_listing_id: v.etsyListingId,
    seo_title: v.seoTitle,
    seo_description: v.seoDescription,
  };

  let id: string;
  if (productId) {
    const { data, error } = await supabase.from("products").update(row).eq("id", productId).select("id");
    if (error) return dbError(error);
    if (!data?.length) return { ok: false, message: "This product no longer exists." };
    id = productId;
  } else {
    const { data, error } = await supabase.from("products").insert(row).select("id").single();
    if (error) return dbError(error);
    id = data.id;
  }

  // Remove images the admin ticked.
  const removeIds = formData.getAll("removeImage").map(String).filter(isUuid);
  if (removeIds.length) {
    const { data: removed } = await supabase
      .from("product_images")
      .delete()
      .eq("product_id", id)
      .in("id", removeIds)
      .select("storage_path");
    const paths = (removed ?? []).map((r) => r.storage_path).filter((p): p is string => Boolean(p));
    if (paths.length) await supabase.storage.from(PRODUCT_IMAGES_BUCKET).remove(paths);
  }

  // Update alt text and order of the remaining images.
  const keptIds = formData
    .getAll("imageId")
    .map(String)
    .filter((imageId) => isUuid(imageId) && !removeIds.includes(imageId));
  for (const imageId of keptIds) {
    const position = Number.parseInt(field(formData, `imagePosition:${imageId}`), 10);
    await supabase
      .from("product_images")
      .update({
        alt: field(formData, `imageAlt:${imageId}`).trim().slice(0, 200) || null,
        position: Number.isFinite(position) ? position : 0,
      })
      .eq("id", imageId)
      .eq("product_id", id);
  }

  // Attach images uploaded straight to Supabase Storage by the browser.
  let newPaths: string[] = [];
  try {
    const raw: unknown = JSON.parse(field(formData, "newImages") || "[]");
    if (Array.isArray(raw)) {
      newPaths = [...new Set(raw.filter((p): p is string => typeof p === "string" && STORAGE_PATH.test(p)))].slice(0, 20);
    }
  } catch {
    newPaths = [];
  }
  if (newPaths.length) {
    // Skip files already attached (e.g. the form was submitted twice).
    const { data: existing } = await supabase
      .from("product_images")
      .select("storage_path, position")
      .eq("product_id", id)
      .order("position", { ascending: false });
    const attached = new Set((existing ?? []).map((r) => r.storage_path));
    newPaths = newPaths.filter((path) => !attached.has(path));
    const start = (existing?.[0]?.position ?? -1) + 1;

    if (newPaths.length) {
      const { error } = await supabase.from("product_images").insert(
        newPaths.map((path, index) => ({
          product_id: id,
          storage_path: path,
          url: supabase.storage.from(PRODUCT_IMAGES_BUCKET).getPublicUrl(path).data.publicUrl,
          alt: v.title,
          position: start + index,
        })),
      );
      if (error) {
        updateTag("products");
        // The product exists now: continue on its edit page rather than risking a duplicate on resubmit.
        if (!productId) redirect(`/admin/products/${id}?created=1&imageError=1`);
        return dbError(error);
      }
    }
  }

  updateTag("products");
  if (!productId) redirect(`/admin/products/${id}?created=1`);
  return { ok: true, message: "Saved ♡ Changes are live on the shop." };
}

export async function deleteProduct(formData: FormData) {
  const { supabase } = await adminContext();
  const id = z.uuid().parse(formData.get("id"));

  const { data: images } = await supabase.from("product_images").select("storage_path").eq("product_id", id);
  const { error } = await supabase.from("products").delete().eq("id", id);
  if (error) throw new Error("Could not delete the product");

  const paths = (images ?? []).map((r) => r.storage_path).filter((p): p is string => Boolean(p));
  if (paths.length) await supabase.storage.from(PRODUCT_IMAGES_BUCKET).remove(paths);

  updateTag("products");
  redirect("/admin/products");
}
